### ISSUE TITLE
create_action_goal_shared() not found

### ISSUE THREAD

**Issue by shouryasrivastava1** [StefanFabian/qml_ros2_plugin#7]
When i try to build the package the ros2.cpp cant find the create_action_goal_shared function as its not a member of babel_fish_ when i checked the babel_fish.hpp which was installed through apt in the ros humble include folder it didnt have that function so i tried to replace the hpp file with the file i found in the babel fish repo with what i had install from apt when i did that i couldnt find logger.hpp so i just cloned the repo and moved the src folder to the opt ro humble directory where the hpp files were then tried to build then the build to like 10 mins and show so many erorrs it took 1 min for it to display all please help

![image](https://github.com/user-attachments/assets/0a34e6b2-2de5-4201-ac15-ffcd544a107d)

**Comment by shouryasrivastava1** [comment]
i have got the shared function in the hpp file now when i downloaded it through apt-get instead of apt but when building it still cant find the function idky

**Comment by StefanFabian** [comment]
Please do not just copy header files between source and debian install.
This will not fix any issues and lead to extremely hard to debug issues in your workspace.

Yes, thank you for bringing this to my attention. This method was indeed not backported to humble.
If you use the debian version (apt install) of qml_ros2_plugin and ros_babel_fish, this issue should not arise.
If you want to build it from source, for the moment you have to go back and checkout this commit 4c2047f44b58b8d887eb51b59c7db4c96b7b3de2
`git checkout 4c2047f`.
I will look into backporting those methods for humble tomorrow but humble is not supported for actions (and services) anyway since the introspection in the ros core libraries still does not work properly despite my backport of the fix being merged a while ago.
If you can, I would recommend switching to jazzy.

**Comment by StefanFabian** [comment]
Fixed on latest humble and iron branches. I have backported all latest changes.
